image: node:latest

stages:
  - testing

variables:
  POSTGRES_DB: gitlab_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

testing:
  services:
    - postgres:latest

  before_script:
    - yarn install
    - yarn knex migrate:latest --env testing
  stage: testing
  script:
    - yarn jest